// frontend/src/components/common/SectionHeader.vue
<script setup lang="ts">
import { cn } from "~/lib/utils";

const props = withDefaults(
  defineProps<{
    class?: string;
    title: string;
    description?: string;
    count?: number | null;
    countLabel?: string;
    icon?: any;
  }>(),
  {
    count: null,
    countLabel: "个",
  },
);

const Icon = props.icon;
</script>

<template>
  <div
    data-slot="section-header"
    :class="cn('flex items-center justify-between gap-3', props.class)"
  >
    <div class="flex min-w-0 flex-col gap-1">
      <div class="flex items-center gap-2">
        <component v-if="Icon" :is="Icon" class="h-5 w-5 shrink-0 text-muted-foreground" />
        <h2 class="truncate font-mono text-xl font-bold text-foreground">{{ title }}</h2>
        <Badge
          v-if="count !== null && count !== undefined"
          variant="secondary"
          class="shrink-0 font-mono"
        >
          {{ count }} {{ countLabel }}
        </Badge>
      </div>
      <p v-if="description" class="text-sm text-muted-foreground">{{ description }}</p>
    </div>
    <div v-if="$slots.actions" class="flex shrink-0 items-center gap-2">
      <slot name="actions" />
    </div>
  </div>
</template>

// frontend/src/lib/components/common/section-header.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { Component } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import { cn, type WithElementRef } from "$lib/utils.js";
  import { Badge } from "$lib/components/ui/badge/index.js";

  type Props = WithElementRef<HTMLAttributes<HTMLDivElement>> & {
    title: string;
    description?: string;
    /** 右上角计数 badge，传数字则显示 */
    count?: number | null;
    countLabel?: string;
    /** 标题前图标组件 */
    icon?: Component<{ class?: string }>;
    /** 右侧操作区（按钮） */
    actions?: Snippet;
  };

  let {
    ref = $bindable(null),
    class: className,
    title,
    description,
    count = null,
    countLabel = "个",
    icon: Icon,
    actions,
    ...restProps
  }: Props = $props();
</script>

<div
  bind:this={ref}
  data-slot="section-header"
  class={cn("flex items-center justify-between gap-3", className)}
  {...restProps}
>
  <div class="flex flex-col gap-1 min-w-0">
    <div class="flex items-center gap-2">
      {#if Icon}
        <Icon class="h-5 w-5 text-muted-foreground shrink-0" />
      {/if}
      <h2 class="text-xl font-bold font-mono text-foreground truncate">{title}</h2>
      {#if count !== null && count !== undefined}
        <Badge variant="secondary" class="font-mono shrink-0">
          {count} {countLabel}
        </Badge>
      {/if}
    </div>
    {#if description}
      <p class="text-sm text-muted-foreground">{description}</p>
    {/if}
  </div>
  {#if actions}
    <div class="flex items-center gap-2 shrink-0">
      {@render actions()}
    </div>
  {/if}
</div>
