// frontend/src/lib/components/ui/spinner/spinner.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js";
	import Loader2Icon from '@lucide/svelte/icons/loader-2';

	let {
		class: className,
		role = "status",
		"aria-label": ariaLabel = "Loading",
	}: { class?: string; role?: string; "aria-label"?: string } = $props();
</script>

<Loader2Icon {role} aria-label={ariaLabel} class={cn("size-4 animate-spin", className)} />

// frontend/src/components/ui/spinner/Spinner.vue
<script setup lang="ts">
import { cn } from "~/lib/utils";
import { Loader2 } from "@lucide/vue";

withDefaults(
  defineProps<{
    class?: string;
    role?: string;
    "aria-label"?: string;
  }>(),
  {
    role: "status",
    "aria-label": "Loading",
  },
);
</script>

<template>
  <Loader2
    :role="role"
    :aria-label="$props['aria-label'] || 'Loading'"
    :class="cn('size-4 animate-spin', $props.class)"
  />
</template>
