// frontend/src/App.vue
<script setup lang="ts">
import { Toaster } from "vue-sonner";

import {
  Cpu,
  Key,
  Globe,
  Users,
  LogOut,
  Sun,
  Moon,
  Boxes,
  PanelLeftClose,
  PanelLeftOpen,
} from "@lucide/vue";

import { useAuthStore } from "~/stores/auth";
import { useThemeStore } from "~/stores/theme";

const router = useRouter();
const route = useRoute();
const authStore = useAuthStore();
const themeStore = useThemeStore();
const { user, loading, isAdmin, isAuthenticated } = storeToRefs(authStore);

// Sidebar collapse state
const sidebarCollapsed = ref(localStorage.getItem("llm-bridge:sidebar-collapsed") === "true");

function toggleSidebar() {
  sidebarCollapsed.value = !sidebarCollapsed.value;
  localStorage.setItem("llm-bridge:sidebar-collapsed", String(sidebarCollapsed.value));
}

// Resolve current page path for active nav highlighting
const currentPath = computed(() => {
  const p = route.path;
  if (p === "/" || p === "/models") return "/models";
  return p;
});

const isAdminRoute = computed(() => {
  return route.meta.requiresAdmin === true;
});

const accessDenied = computed(() => isAdminRoute.value && !isAdmin.value);

const memberNavItems = [
  { path: "/models", label: "模型目录", icon: Cpu },
  { path: "/tokens", label: "API Token", icon: Key },
];

const adminNavItems = [
  { path: "/admin/models", label: "模型管理", icon: Boxes },
  { path: "/providers", label: "提供者管理", icon: Globe },
  { path: "/users", label: "用户管理", icon: Users },
];

const currentLabel = computed(() => {
  return (
    [...memberNavItems, ...adminNavItems].find((n) => n.path === currentPath.value)?.label || ""
  );
});

function navigate(path: string) {
  router.push(path);
}

function handleLogout() {
  authStore.logout();
}
</script>

<template>
  <!-- Loading state -->
  <div v-if="loading" class="flex h-screen items-center justify-center bg-background">
    <div class="h-8 w-8 animate-spin rounded-full border-2 border-[#22C55E] border-t-transparent" />
  </div>

  <!-- Not authenticated -->
  <div v-else-if="!isAuthenticated" class="flex h-screen items-center justify-center bg-background">
    <router-view />
  </div>

  <!-- Authenticated layout -->
  <div v-else class="flex h-svh overflow-hidden">
    <!-- Sidebar -->
    <aside
      :class="[
        'flex shrink-0 flex-col border-r border-border bg-sidebar transition-all duration-200',
        sidebarCollapsed ? 'w-[3.25rem]' : 'w-56',
      ]"
    >
      <!-- Header -->
      <div class="flex items-center gap-2.5 border-b border-border/50 px-3 py-3">
        <div
          :class="[
            'flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#22C55E] font-mono text-sm font-bold text-black',
            sidebarCollapsed ? 'mx-auto' : '',
          ]"
        >
          LB
        </div>
        <span
          v-if="!sidebarCollapsed"
          class="overflow-hidden font-mono text-sm font-semibold whitespace-nowrap"
          >LLM Bridge</span
        >
      </div>

      <!-- Nav -->
      <nav class="flex-1 overflow-y-auto py-2">
        <div class="mb-1 px-2">
          <span v-if="!sidebarCollapsed" class="px-2 text-xs font-medium text-muted-foreground"
            >菜单</span
          >
        </div>
        <button
          v-for="item in memberNavItems"
          :key="item.path"
          @click="navigate(item.path)"
          :title="sidebarCollapsed ? item.label : ''"
          :class="[
            'mb-0.5 flex w-full items-center gap-2 rounded-md px-3 py-2 text-sm transition-colors',
            currentPath === item.path
              ? 'bg-accent font-medium text-accent-foreground'
              : 'text-muted-foreground hover:bg-accent/50 hover:text-foreground',
            sidebarCollapsed ? 'justify-center' : '',
          ]"
        >
          <component :is="item.icon" class="h-4 w-4 shrink-0" />
          <span v-if="!sidebarCollapsed" class="whitespace-nowrap">{{ item.label }}</span>
        </button>

        <template v-if="isAdmin">
          <div class="mt-4 mb-1 px-2">
            <span v-if="!sidebarCollapsed" class="px-2 text-xs font-medium text-muted-foreground"
              >管理</span
            >
          </div>
          <button
            v-for="item in adminNavItems"
            :key="item.path"
            @click="navigate(item.path)"
            :title="sidebarCollapsed ? item.label : ''"
            :class="[
              'mb-0.5 flex w-full items-center gap-2 rounded-md px-3 py-2 text-sm transition-colors',
              currentPath === item.path
                ? 'bg-accent font-medium text-accent-foreground'
                : 'text-muted-foreground hover:bg-accent/50 hover:text-foreground',
              sidebarCollapsed ? 'justify-center' : '',
            ]"
          >
            <component :is="item.icon" class="h-4 w-4 shrink-0" />
            <span v-if="!sidebarCollapsed" class="whitespace-nowrap">{{ item.label }}</span>
          </button>
        </template>
      </nav>

      <!-- Footer -->
      <div class="flex flex-col gap-1 border-t border-border/50 p-2">
        <div v-if="user && !sidebarCollapsed" class="px-2">
          <span class="font-mono text-xs text-muted-foreground">{{ user.name }}</span>
        </div>
        <button
          @click="themeStore.toggle()"
          :title="themeStore.mode === 'dark' ? '切换到白天模式' : '切换到黑夜模式'"
          :class="[
            'flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-xs text-muted-foreground transition-colors hover:bg-accent/50 hover:text-foreground',
            sidebarCollapsed ? 'justify-center' : '',
          ]"
        >
          <Sun v-if="themeStore.mode === 'dark'" class="h-4 w-4" />
          <Moon v-else class="h-4 w-4" />
          <span v-if="!sidebarCollapsed">{{
            themeStore.mode === "dark" ? "白天模式" : "黑夜模式"
          }}</span>
        </button>
        <button
          @click="handleLogout"
          :class="[
            'flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-xs text-muted-foreground transition-colors hover:bg-accent/50 hover:text-foreground',
            sidebarCollapsed ? 'justify-center' : '',
          ]"
        >
          <LogOut class="h-4 w-4" />
          <span v-if="!sidebarCollapsed">退出登录</span>
        </button>
      </div>
    </aside>

    <!-- Main area -->
    <div class="flex min-w-0 flex-1 flex-col overflow-hidden">
      <header class="flex h-12 shrink-0 items-center gap-2 border-b border-border px-4">
        <button
          @click="toggleSidebar"
          class="rounded-md p-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
          aria-label="Toggle sidebar"
        >
          <PanelLeftOpen v-if="sidebarCollapsed" class="h-4 w-4" />
          <PanelLeftClose v-else class="h-4 w-4" />
        </button>
        <span class="font-mono text-sm font-medium text-muted-foreground">{{ currentLabel }}</span>
      </header>
      <main class="flex min-h-0 flex-1 flex-col overflow-hidden p-6">
        <!-- Admin route guard -->
        <UnauthorizedPage v-if="accessDenied" />
        <router-view v-else v-slot="{ Component, route }">
          <Transition name="page" mode="out-in">
            <div class="mx-auto w-full max-w-5xl" :key="route.path">
              <component :is="Component" />
            </div>
          </Transition>
        </router-view>
      </main>
    </div>
  </div>

  <Toaster />
  <ConfirmDialog />
</template>

// frontend/src/App.svelte
<script lang="ts">
  import Router from "svelte-spa-router";
  import { push, router } from "svelte-spa-router";
  import * as Sidebar from "$lib/components/ui/sidebar/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import { Spinner } from "$lib/components/ui/spinner/index.js";
  import { auth } from "$lib/stores/auth.svelte";
  import { theme } from "$lib/stores/theme.svelte";
  import ModelsPage from "./lib/ModelsPage.svelte";
  import TokensPage from "./lib/TokensPage.svelte";
  import ProvidersPage from "./lib/ProvidersPage.svelte";
  import UsersPage from "./lib/UsersPage.svelte";
  import LoginPage from "./lib/LoginPage.svelte";
  import AdminModelsPage from "./lib/AdminModelsPage.svelte";
  import { Cpu, Key, Globe, Users, LogOut, Sun, Moon, Boxes } from "@lucide/svelte";

  type PagePath = "/models" | "/tokens" | "/providers" | "/users" | "/admin/models";

  const routes = {
    "/": ModelsPage,
    "/models": ModelsPage,
    "/tokens": TokensPage,
    "/providers": ProvidersPage,
    "/users": UsersPage,
    "/admin/models": AdminModelsPage,
    "/login": LoginPage,
  };

  const resolveCurrentPage = (path: string): PagePath | "/login" => {
    if (path === "/login") return "/login";
    if (path === "/" || path === "/models") return "/models";
    if (path === "/tokens") return "/tokens";
    if (path === "/providers") return "/providers";
    if (path === "/users") return "/users";
    if (path === "/admin/models") return "/admin/models";
    return "/models";
  };

  let currentPath = $derived(resolveCurrentPage(router.location));

  function navigate(path: PagePath | "/login") {
    push(path);
  }

  // Auth loading state
  let showApp = $derived(!auth.loading);
  let isAuthenticated = $derived(auth.isAuthenticated);
  let isAdmin = $derived(auth.isAdmin);

  const memberNavItems = [
    { path: "/models" as const, label: "模型目录", icon: Cpu },
    { path: "/tokens" as const, label: "API Token", icon: Key },
  ];

  const adminNavItems = [
    { path: "/admin/models" as const, label: "模型管理", icon: Boxes },
    { path: "/providers" as const, label: "提供者管理", icon: Globe },
    { path: "/users" as const, label: "用户管理", icon: Users },
  ];

  function getCurrentLabel(path: string): string {
    return [...memberNavItems, ...adminNavItems].find((n) => n.path === path)?.label || "";
  }
</script>

{#if !showApp}
  <div class="flex h-screen items-center justify-center bg-background">
    <Spinner class="h-8 w-8 text-[#22C55E]" />
  </div>
{:else if !isAuthenticated}
  <LoginPage />
{:else}
  <Sidebar.Provider class="h-svh overflow-hidden">
    <Sidebar.Root collapsible="icon">
      <Sidebar.Header>
        <div
          class="flex items-center gap-2.5 px-2 py-1.5 group-data-[collapsible=icon]:gap-0 group-data-[collapsible=icon]:justify-center group-data-[collapsible=icon]:px-0"
        >
          <div
            class="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#22C55E] text-black text-sm font-bold font-mono"
          >
            LB
          </div>
          <span
            class="text-sm font-semibold font-mono overflow-hidden whitespace-nowrap transition-[opacity,max-width] duration-200 ease-linear group-data-[state=collapsed]:opacity-0 group-data-[state=collapsed]:max-w-0 group-data-[state=expanded]:opacity-100 group-data-[state=expanded]:max-w-[200px]"
            >LLM Bridge</span
          >
        </div>
      </Sidebar.Header>
      <Sidebar.Content>
        <Sidebar.Group>
          <Sidebar.GroupLabel>菜单</Sidebar.GroupLabel>
          <Sidebar.Menu>
            {#each memberNavItems as item}
              <Sidebar.MenuItem>
                <Sidebar.MenuButton
                  isActive={currentPath === item.path}
                  onclick={() => navigate(item.path)}
                  tooltipContent={item.label}
                >
                  <item.icon class="h-4 w-4" />
                  <span
                    class="overflow-hidden whitespace-nowrap transition-[opacity,max-width] duration-200 ease-linear group-data-[state=collapsed]:opacity-0 group-data-[state=collapsed]:max-w-0 group-data-[state=expanded]:opacity-100 group-data-[state=expanded]:max-w-[200px]"
                    >{item.label}</span
                  >
                </Sidebar.MenuButton>
              </Sidebar.MenuItem>
            {/each}
          </Sidebar.Menu>
        </Sidebar.Group>
        {#if isAdmin}
          <Sidebar.Group>
            <Sidebar.GroupLabel>管理</Sidebar.GroupLabel>
            <Sidebar.Menu>
              {#each adminNavItems as item}
                <Sidebar.MenuItem>
                  <Sidebar.MenuButton
                    isActive={currentPath === item.path}
                    onclick={() => navigate(item.path)}
                    tooltipContent={item.label}
                  >
                    <item.icon class="h-4 w-4" />
                    <span
                      class="overflow-hidden whitespace-nowrap transition-[opacity,max-width] duration-200 ease-linear group-data-[state=collapsed]:opacity-0 group-data-[state=collapsed]:max-w-0 group-data-[state=expanded]:opacity-100 group-data-[state=expanded]:max-w-[200px]"
                      >{item.label}</span
                    >
                  </Sidebar.MenuButton>
                </Sidebar.MenuItem>
              {/each}
            </Sidebar.Menu>
          </Sidebar.Group>
        {/if}
      </Sidebar.Content>
      <Sidebar.Footer>
        <div class="flex flex-col gap-2 px-2 py-2">
          {#if auth.user}
            <div
              class="text-xs text-muted-foreground overflow-hidden whitespace-nowrap transition-[opacity,max-width] duration-200 ease-linear group-data-[state=collapsed]:opacity-0 group-data-[state=collapsed]:max-w-0 group-data-[state=expanded]:opacity-100 group-data-[state=expanded]:max-w-[200px]"
            >
              <span class="font-mono text-foreground">{auth.user.name}</span>
            </div>
          {/if}
          <Button
            variant="ghost"
            size="sm"
            class="justify-start gap-2 text-muted-foreground hover:text-foreground cursor-pointer group-data-[collapsible=icon]:justify-center group-data-[collapsible=icon]:px-1"
            onclick={() => theme.toggle()}
            aria-label={theme.isDark ? "切换到白天模式" : "切换到黑夜模式"}
            title={theme.isDark ? "切换到白天模式" : "切换到黑夜模式"}
          >
            {#if theme.isDark}
              <Sun class="h-4 w-4" />
            {:else}
              <Moon class="h-4 w-4" />
            {/if}
            <span
              class="overflow-hidden whitespace-nowrap transition-[opacity,max-width] duration-200 ease-linear group-data-[state=collapsed]:opacity-0 group-data-[state=collapsed]:max-w-0 group-data-[state=expanded]:opacity-100 group-data-[state=expanded]:max-w-[200px]"
              >{theme.isDark ? "白天模式" : "黑夜模式"}</span
            >
          </Button>
          <Button
            variant="ghost"
            size="sm"
            class="justify-start gap-2 text-muted-foreground hover:text-foreground cursor-pointer group-data-[collapsible=icon]:justify-center group-data-[collapsible=icon]:px-1"
            onclick={() => auth.logout()}
          >
            <LogOut class="h-4 w-4" />
            <span
              class="overflow-hidden whitespace-nowrap transition-[opacity,max-width] duration-200 ease-linear group-data-[state=collapsed]:opacity-0 group-data-[state=collapsed]:max-w-0 group-data-[state=expanded]:opacity-100 group-data-[state=expanded]:max-w-[200px]"
              >退出登录</span
            >
          </Button>
        </div>
      </Sidebar.Footer>
    </Sidebar.Root>
    <Sidebar.Inset class="overflow-hidden min-h-0">
      <header class="flex h-12 shrink-0 items-center gap-2 border-b border-border px-4">
        <Sidebar.Trigger class="-ml-1" />
        <span class="text-sm font-medium text-muted-foreground font-mono">
          {getCurrentLabel(currentPath)}
        </span>
      </header>
      <main class="flex-1 min-h-0 overflow-hidden p-6 flex flex-col">
        <Router {routes} />
      </main>
    </Sidebar.Inset>
  </Sidebar.Provider>
{/if}
